apiVersion: v2
name: postgres
description: run PostgeSQL rootless on k8s
type: application
version: 1.0.0
home: https://github.com/11notes/docker-postgres
sources:
  - https://github.com/11notes/docker-postgres
keywords:
  - postgres
  - postgresql
  - database
maintainers:
  - name: 11notes
