image:
  # ╔═════════════════════════════════════════════════════╗
  # ║   Since this repo contains 15, 16, 17 and 18 of     ║
  # ║   postgres and uses the same chart for all of       ║
  # ║   these please set the desired version via tag      ║
  # ╚═════════════════════════════════════════════════════╝
  repository: 11notes/postgres
  tag: "18"
  pullPolicy: IfNotPresent

replicaCount: 1
nameOverride: ""
fullnameOverride: ""
timezone: "Europe/Zurich"

postgres:
  # ╔═════════════════════════════════════════════════════╗
  # ║   Either set password and a k8s secret will be      ║
  # ║   created or set an existing secret holding the     ║
  # ║   POSTGRES_PASSWORD secret                          ║
  # ╚═════════════════════════════════════════════════════╝
  password: ""
  existingSecret: ""
  existingSecretKey: "POSTGRES_PASSWORD"
  backupSchedule: ""
  backupRetention: ""

extraEnv: []

service:
  type: ClusterIP
  port: 5432
  nodePort: ""
  annotations: {}

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}

tmpfs:
  run:
    sizeLimit: ""
  log:
    sizeLimit: ""

persistence:
  etc:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 16Mi
  var:
    enabled: true
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 32Gi
  backup:
    enabled: false
    existingClaim: ""
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 64Gi

livenessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  exec:
    command:
      - pg_isready
      - -U
      - postgres
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6