services:
  postgres:
    image: "11notes/postgres:16"
    container_name: "postgres"
    environment:
      TZ: "Europe/Zurich"
      POSTGRES_PASSWORD: "*********"
    ports:
      - "5432:5432/tcp"
    volumes:
      - "var:/postgres/var"
      - "backup:/postgres/backup"
    restart: "always"
volumes:
  var:
  backup: