name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:   
      - name: build docker image
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4 #v1.3.1
        with:
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "release":"true", "readme":"true" }'